Repository FrancoTastaca/recalc, pull requests merged in 2023-05, with the labels that each got.

#6 test: Se agrega los test necesarios que comprueba que el resultado sea un numero negativo
  test/core.test.js
Labels: enhancement

#7 Test: se añadio el test para div
  test/core.test.js
Labels: enhancement

#9 Test: se añadio test para pow
  test/core.test.js
Labels: enhancement

#10 Feat: se añadio endpoint para pow
  src/controllers.js
Labels: enhancement

#11 Test: se añadio test opcional para pow
  test/core.test.js
Labels: enhancement

#12 Test: se añadio test opcional para sub
  test/core.test.js
Labels: enhancement

#13 Test: se añadio el test opcional para div
  test/core.test.js
Labels: enhancement

#14 Feature/implementacion throw
  src/controllers.js
  test/core.test.js
Labels: enhancement

#15 Feature: refactor de tests
  src/controllers.js
  test/core.test.js
Labels: refactor

#16 Feature: bug segundo parametro tabla history
  src/models.js
  test/models.test.js
Labels: bug

#18 Feature: getHistory y test
  src/models.js
  test/models.test.js
Labels: enhancement, test

#17 Feature: endpoint de Suma y test de status
  src/controllers.js
  test/api.test.js
Labels: enhancement, test

#19 Feature: endpoint multiplicacion y comprobacion del mismo con un test
  src/controllers.js
  test/api.test.js
Labels: enhancement, test

#22 Feature/atributo error - test
  src/models.js
  test/models.test.js
Labels: test, refactor

#20 Feature: Correccion de bug de feature/Mul
  src/controllers.js
  src/models.js
  test/api.test.js
Labels: bug

#23 Feature/eliminar historial - test
  src/models.js
  test/models.test.js
Labels: enhancement, test

#24 Feature/endpoint div - test - status
  src/controllers.js
  test/api.test.js
Labels: test, refactor

#25 Feature/endpoint pow - test - status
  src/controllers.js
  test/api.test.js
Labels: test, refactor

#26 test: El request del endpoint suma con 0.1 y 0.2 tenga como resultado 0.3
  test/api.test.js
Labels: test

#27 Feature: Opcional - Agregar operación sqrt al core y hacer un endpoint con el test correspondiente
  src/controllers.js
  src/core.js
  src/seed.js
  test/api.test.js
  test/core.test.js
Labels: enhancement, test

#28 Feature/endpoint modificaciones
  src/controllers.js
  src/models.js
  test/api.test.js
  test/core.test.js
Labels: refactor

#29 Feature/funcion ftb opcional - endpoint - test
  src/controllers.js
  src/core.js
  src/seed.js
  test/api.test.js
  test/core.test.js
Labels: enhancement, test
